name: luna_arc_sync
description: "泠月案阁 - Luna Arc Sync"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1

  dio: ^5.4.3+1

  get_it: ^8.2.0
  injectable: ^2.5.2

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  flutter_secure_storage: ^9.2.4

  file_picker: ^10.3.2

  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.4
  material_tag_editor: ^0.1.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  file_saver: ^0.3.1
  image_cropper: ^11.0.0
  image: ^4.5.4
  cunning_document_scanner: ^1.3.1 # NEW: Document scanner alternative
  path_provider: ^2.0.17
  image_cropper_platform_interface: ^8.0.0
  flutter_inappwebview: ^6.1.5 # WebView for PDF.js rendering (Apache 2.0 license)
  pdfx: ^2.7.0 # High quality PDF rendering (MIT license)
  pdfrx: ^2.2.0 # Modern PDF rendering with advanced features (MIT license)
  path: ^1.9.0
  bloc: ^9.0.1
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.2
  http: ^1.2.2              # For network scanner HTTP communication
  xml: ^6.5.0               # Parse eSCL/IPP XML responses
  network_info_plus: ^6.0.0 # Network scanner discovery
  multicast_dns: ^0.3.2+8   # mDNS service discovery

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.9.0
  freezed: ^3.2.3
  injectable_generator: ^2.9.0
  json_serializable: ^6.11.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: LXGWWenKaiMono
      fonts:
        - asset: assets/fonts/LXGWWenKaiMono-Regular.ttf

dependency_overrides:
  photo_view: ^0.15.0